In [5]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle
#import sklearn test_train_split
from sklearn.model_selection import train_test_split

In [6]:
#load the dataset named data.csv and print the first 5 rows
data = pd.read_csv('data.csv')
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [7]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

/tmp/ipykernel_19028/791956819.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In [9]:
#check the columns of the dataset
print(data.columns)

Index(['G1', 'G2', 'G3', 'studytime', 'failures', 'absences'], dtype='object')


In [8]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [10]:
linear_regression = LinearRegression()

In [11]:
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8865884925774817


In [12]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 6.90952723 15.33571881  7.00251232  8.28794566 15.33571881]
 [ 6.90952723  6.90952723  7.00251232  8.28794566 12.95707371]
 [ 9.20918595 15.06593267  7.00251232 11.44423389  4.31172278]
 ...
 [ 4.31172278 15.06593267  6.0034947  11.44423389 11.44423389]
 [-1.62933637  9.57337899  6.0034947   8.28794566  8.28794566]
 [15.06593267  8.27372756  6.0034947   8.28794566  6.90952723]] [[[ 6  8  1  3 16]
  [16 15  2  0  2]
  [ 7  8  2  0  0]
  [ 9  9  2  0  0]
  [16 15  2  0  2]]

 [[ 6  8  1  3 16]
  [ 6  8  1  3 16]
  [ 7  8  2  0  0]
  [ 9  9  2  0  0]
  [14 13  3  1 12]]

 [[ 9 10  3  0  4]
  [16 15  3  0  0]
  [ 7  8  2  0  0]
  [12 11  1  0 16]
  [ 6  5  1  0  7]]

 ...

 [[ 6  5  1  0  7]
  [16 15  3  0  0]
  [ 7  7  3  0  6]
  [12 11  1  0 16]
  [12 11  1  0 16]]

 [[ 4  0  1  2  0]
  [11 10  2  0  0]
  [ 7  7  3  0  6]
  [ 9  9  2  0  0]
  [ 9  9  2  0  0]]

 [[16 15  3  0  0]
  [ 8  9  2  0  4]
  [ 7  7  3  0  6]
  [ 9  9  2  0  0]
  [ 6  8  1  3 16]]] [array([[ 8, 15,  0, 10, 15]

In [16]:
#ask the student the grades based on the input and use the model to predict the grades
G1 = int(input("Enter the first grade: "))
G2 = int(input("Enter the second grade: "))    
studytime = int(input("Enter the study time: "))
failures = int(input("Enter the number of failures: "))
absences = int(input("Enter the number of absences: "))
prediction = linear_regression.predict([[G1, G2, studytime, failures, absences]])
print(prediction)


[98.08845295]
