In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [2]:
data = pd.read_csv("data.csv")

data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

In [3]:
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

/tmp/ipykernel_19666/2796477508.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


In [4]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [5]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)

LinearRegression()

In [7]:
#print the model accuracy
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8255022805521344


In [8]:

import pickle
with open("pickle_model", "wb") as file:
    pickle.dump(linear_regression, file)

In [9]:
with open("pickle_model", "rb") as file:
    model = pickle.load(file)

predictions = model.predict(xtest)

for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 6.40140663  9.61161682 13.86392726 10.95164983  9.61161682]
 [ 6.40140663  6.40140663 13.86392726 10.95164983 12.75552298]
 [ 7.74957793  8.52455821 13.86392726  7.37976972 10.9974912 ]
 ...
 [10.9974912   8.52455821 12.95421739  7.37976972  7.37976972]
 [ 9.77767724 11.78984925 12.95421739 10.95164983 10.95164983]
 [ 8.52455821  8.42261564 12.95421739 10.95164983  6.40140663]] [[[ 8  7  1  0  0]
  [11 10  2  0  0]
  [13 14  3  0  6]
  [10 11  1  0  8]
  [11 10  2  0  0]]

 [[ 8  7  1  0  0]
  [ 8  7  1  0  0]
  [13 14  3  0  6]
  [10 11  1  0  8]
  [10 13  1  0  4]]

 [[ 7  9  3  0  0]
  [ 7 10  3  1  0]
  [13 14  3  0  6]
  [ 8  8  1  0  0]
  [13 11  2  0  2]]

 ...

 [[13 11  2  0  2]
  [ 7 10  3  1  0]
  [13 13  2  0  2]
  [ 8  8  1  0  0]
  [ 8  8  1  0  0]]

 [[10 10  2  1 14]
  [11 12  1  0  0]
  [13 13  2  0  2]
  [10 11  1  0  8]
  [10 11  1  0  8]]

 [[ 7 10  3  1  0]
  [ 9  9  1  2  8]
  [13 13  2  0  2]
  [10 11  1  0  8]
  [ 8  7  1  0  0]]] [array([[ 6, 10, 14, 10, 10]

In [13]:
#i want to use the saved picke  model to predict the value from the user with input keywoard and print the result using the model 

# Path: model_save/predict.ipynb
import pickle
import numpy as np

with open("pickle_model", "rb") as file:
    model = pickle.load(file)

G1 = int(input("Enter G1: "))
G2 = int(input("Enter G2: "))
studytime = int(input("Enter studytime: "))
failures = int(input("Enter failures: "))
absences = int(input("Enter absences: "))
x = np.array([[G1, G2, studytime, failures, absences]])
predictions = model.predict(x)
print(predictions)



/tmp/ipykernel_19666/2706571931.py:12: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  x = np.array(data.drop([predict], 1))


[[15.54773441 11.73388539  6.76470524  4.93418967 11.73388539]
 [15.54773441 15.54773441  6.76470524  4.93418967  8.93675791]
 [ 4.12136897 18.26623349  6.76470524 14.04215901  7.48934825]
 ...
 [ 7.48934825 18.26623349  3.87940007 14.04215901 14.04215901]
 [11.3341474  14.31962911  3.87940007  4.93418967  4.93418967]
 [18.26623349 15.00005944  3.87940007  4.93418967 15.54773441]] [[[15 15  2  0 10]
  [12 12  2  0  0]
  [ 7  8  2  3 10]
  [ 5  6  2  0  6]
  [12 12  2  0  0]]

 [[15 15  2  0 10]
  [15 15  2  0 10]
  [ 7  8  2  3 10]
  [ 5  6  2  0  6]
  [ 6 10  2  0  4]]

 [[ 6  5  2  0  6]
  [16 18  2  0  0]
  [ 7  8  2  3 10]
  [15 14  3  0  2]
  [10  8  2  0  0]]

 ...

 [[10  8  2  0  0]
  [16 18  2  0  0]
  [ 5  5  2  0  4]
  [15 14  3  0  2]
  [15 14  3  0  2]]

 [[10 12  3  0  4]
  [14 14  1  0  2]
  [ 5  5  2  0  4]
  [ 5  6  2  0  6]
  [ 5  6  2  0  6]]

 [[16 18  2  0  0]
  [14 15  2  0  0]
  [ 5  5  2  0  4]
  [ 5  6  2  0  6]
  [15 15  2  0 10]]] [array([[15, 11, 10,  6, 11]